services:

  steam-inventory-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      WEBSHARE_API_KEY: ${WEBSHARE_API_KEY}
      AUTH_TOKEN: ${AUTH_TOKEN}
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge